# Generated by Django 4.2.16 on 2024-12-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_created_by_brand_created_on_brand_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='max_percentage',
        ),
        migrations.AddField(
            model_name='sizechart',
            name='max_percentage',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
