# Generated by Django 4.2.16 on 2025-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_max_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='classification',
            field=models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Girl', 'Girl'), ('Boy', 'Boy')], db_index=True, default='Men', max_length=10),
            preserve_default=False,
        ),
    ]
