# Generated by Django 4.2.16 on 2025-03-10 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_category_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this item was originally created')),
                ('last_updated_on', models.DateTimeField(auto_now=True, help_text='When this item was last modified')),
                ('is_deleted', models.BooleanField(default=False, help_text='use this for soft deleting')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=250)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user which originally created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creations', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='The user which last modified this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
