# Generated by Django 4.2.16 on 2025-04-19 18:16

import colorfield.fields
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.get_product_image_path)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
