# Generated by Django 4.2.16 on 2025-04-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcolor_productsizechart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
        ),
        migrations.AddField(
            model_name='productsizechart',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='product.productcolor'),
        ),
        migrations.AddField(
            model_name='productsizechart',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_chart', to='product.sizechart'),
        ),
    ]
