# Generated by Django 4.2.16 on 2025-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateTimeField(auto_now=True, help_text='When this item was ordered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_quantity',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
