# Generated by Django 4.2.16 on 2025-04-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_order_gateway_order_id_order_gateway_payment_id_and_more'),
        ('product', '0006_productcolor_productsizechart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='product.productsizechart'),
        ),
    ]
