# Generated by Django 4.2.16 on 2024-10-10 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user which originally created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this item was originally created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='use this for soft deleting'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, help_text='The user which last modified this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True, help_text='When this item was last modified'),
        ),
    ]
